### PR TITLE
Update runtime

### PR DESCRIPTION
**Pull request by TingPing**

### CODE REVIEW

**Comment by TingPing** [comment]
bot, build

**Comment by TingPing** [comment]
bot, build

**Comment by aral** [comment]
@TingPing Thanks for this. This repository is [automatically generated](https://github.com/indie-mirror/gnomit/blob/master/publish-to-flathub) from [the main Gnomit repository](https://source.ind.ie/gnome/gnomit/gjs/) which has [a GitHub mirror](https://github.com/indie-mirror/gnomit ) where I’m happy to receive issues, patches and pull requests :)

I’m going to implement these in the main repository for the next release.

Regarding which version of the runtime to use and when to update it, are there any guidelines you know of for Flatpak/Flathub. The runtimes are rather large so when is the recommended time to update a Gnome runtime, for example? Is it when it hits X amount of distributions or particular distributions or LTS versions or… (so that most people aren’t downloading hundreds of megabytes just to get it).

**Comment by aral** [comment]
Implemented in https://github.com/flathub/ind.ie.Gnomit/commit/0c8365081d71802205085ca3f691d33d10318e5f

Thank you for your help, @TingPing – I appreciate it :)

**Pull request closed without merging**
